config:
    appDebug: true or false (show debug details for exemptions)
    database:
        dbHost: localhost
        dbName: phpblog
        dbUser: root
        dbPwd:
    posts:
        postPerPage: 5 (integer - post quantity per page for posts list)
    googleRecaptcha:
        siteKey: your_site_key
        secretKey: your_secret_key
    contactForm:
        ajaxMode: true or false
        contactEmail: your_email_address_to_receive_contact_message
